### PR TITLE
Update cfitsio to v3.43: includes critical bug fix

### LINKED ISSUE #7272: Security: please update cfitsio
A new version of cfitsio just came out, accompanied with the [following notice from upstream](https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes2.txt):

>The NASA security team requires the following warning to all users of CFITSIO:
>
>_The CFITSIO open source software project contains vulnerabilities that could allow a remote, unauthenticated attacker to take control of a server running the CFITSIO software.  These vulnerabilities affect all servers and products running the CFITSIO software.
> The CFITSIO team has released software updates to address these vulnerabilities.  There are no workarounds to address these vulnerabilities.  In all cases, the CFITSIO team is recommending an immediate update to resolve the issues._

It is still unclear what the exact problem is (see discussion in Debian bug [#892458](https://bugs.debian.org/892458)), but it may be wise to update cfitsio in 3.X and 2.X and to create a new point release.

### PR DESCRIPTION
**Pull request by drdavella**
This fixes #7272. I'll open a separate PR for backporting to 2.0.x.

### CODE REVIEW

**Comment by MSeifert04** [comment]
LGTM provided the tests pass. 

Just a question: Why the euv variable in the script? :D

**Comment by drdavella** [comment]
@MSeifert04 the script wasn't working for me at first, so I added those flags to help me debug it. I forgot to remove them before committing but it seems like there's no reason to remove them at this point:

http://tldp.org/LDP/abs/html/options.html

**Comment by mhvk** [comment]
Happy to see you found my script (and sorry that it didn't work immediately...)

File: cextern/trim_cfitsio.sh [hunk 1]
```diff
@@ -29,7 +31,7 @@ rm -f cfitsio/docs/*.ps
 rm -f cfitsio/docs/*.pdf
 rm -f cfitsio/docs/*.doc
 rm -f cfitsio/docs/*.toc
-rm -f cfitsio/[^L]*.*
+rm -rf cfitsio/[^L]*.*
```
Comment (mhvk) [inline cextern/trim_cfitsio.sh]: I'm surprised by the need for this change - this means that in the new `cfitsio` library there is a directory with a `.` in its name. Out of curiosity, what is it?

Comment (pllim) [reply cextern/trim_cfitsio.sh]: I guess I should wait till this is answered before merging?

Comment (drdavella) [reply cextern/trim_cfitsio.sh]: For me it was `cfitsio/cfitsio.xcodeproj`, which appears to be generated when building (on OSX for me). Maybe we should just explicitly remove that file rather than using `-rf` here?

Comment (mhvk) [reply cextern/trim_cfitsio.sh]: So, that must be a new directory. I think I'd prefer removing it explicitly, but honestly I don't really know why...

**Comment by eteq** [comment]
Alright, all passed and approved, so merging now.
