### PR TITLE
Fix segfault with error report in FITS compression

### LINKED ISSUE #15482: Version 5.3 fails to read large CompImageHDUs
### Description

Large FITS files with produced with the JSOC mtrack module ([http://hmi.stanford.edu/rings/modules/mtrack.html](http://hmi.stanford.edu/rings/modules/mtrack.html)) cannot be read with astropy 5.3.0--5.3.4. 

The issue occurs only when the fits file contains a large CompImageHDU. In the example below, the data of size [641,1700,1700] are stored using the `HCOMPRESS_1` compression method. But also other compression methods (e.g. `RICE`) share the same issue.

### Expected behavior

There should be no coredump (segmentation fault) when accessing the data in the CompImageHDU.

### How to Reproduce

1. Download the sample file from my Dropbox (2.7 Gbyte): [Vcomp.fits](https://www.dropbox.com/scl/fi/m1jruw8esipdtsh4vkh82/Vcomp.fits?rlkey=k5svmo3hdigoslk9ty0t1ajsm&dl=1).
2. Open the file, and try to access the CompImageHDU:
```
from astropy.io import fits

hdu = fits.open('Vcomp.fits')
shape = hdu[1].data.shape
```
3. With astropy 5.3.x I get the following error:
```
zsh: segmentation fault  ipython

/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
4.  The error could be reproduced on MacOS 14, python version 3.11, and on 2 different linux workstations (x86_64 architecture) with python 3.9--3.12 (see example configurations in the version section below).
5. There is no problem when reading in the file with astropy 5.1 or 5.2.  
6. There's no proble for smaller files produced with the same mtrack tool (e.g. 50 frames instead of 641 frames).

### Versions

macOS-14.0-arm64-arm-64bit
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
astropy 5.3.4

Linux-4.18.0-372.70.1.1.el8_6.x86_64-x86_64-with-glibc2.28
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
astropy 5.3

### PR DESCRIPTION
**Pull request by saimn**
ffpmsg requires the GIL.

Fix #15482

### Description

This pull request is to address ...

Fixes #<Issue Number>

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

File: astropy/io/fits/hdu/compressed/src/compression.c [hunk 1]
```diff
@@ -90,7 +90,10 @@ PyInit__compression(void)
 // cfitsio call.  In our wrapper functions we can then check if the Python error
 // state is set and then return NULL to raise the error.
 void ffpmsg(const char *err_message) {
+    PyGILState_STATE gstate;
+    gstate = PyGILState_Ensure();
     PyErr_SetString(CfitsioException, err_message);
+    PyGILState_Release(gstate);
```
Comment (Cadair) [inline astropy/io/fits/hdu/compressed/src/compression.c:96]: Is this assuming that we are always releasing the GIL when calling out to cfitsio? If for some reason that were to change would it explode?

**Comment by Cadair** [comment]
Don't suppose you have any bright ideas on how we could test this? I am pretty sure I ran screaming from the idea of testing the error stuff when I originally wrote this.

**Comment by saimn** [comment]
Not really, I guess we could create a file that would trigger the warnings/errors but not sure how.

File: astropy/io/fits/hdu/compressed/src/compression.c (hunk 1 above)
Comment (astrofrog) [reply astropy/io/fits/hdu/compressed/src/compression.c:96]: Not releasing the GIL would mean no longer being able to do multithreaded decompression of tiles which does work at the moment.

Comment (saimn) [reply astropy/io/fits/hdu/compressed/src/compression.c:96]: So I guess the fix here is fine for now, but we may have to reconsider when subinterpreters become a thing (planned for 3.13) ?

Comment (Cadair) [reply astropy/io/fits/hdu/compressed/src/compression.c:96]: > If you need to call Python code from these threads (often this will be part of a callback API provided by the aforementioned third-party library), you must first register these threads with the interpreter by creating a thread state data structure, then acquiring the GIL, and finally storing their thread state pointer, before you can start using the Python/C API. When you are done, you should reset the thread state pointer, release the GIL, and finally free the thread state data structure.

Nope, I am out lol too much C :rofl:

**Review by Cadair — APPROVED** [review]

**Comment by pllim** [comment]
I cannot tell if more fixes are needed or not based on Simon's comment in that issue, so I'll let @saimn decide when to merge. Thanks, all!

**Comment by astrofrog** [comment]
I think I have an idea for a regression test - please don't merge yet so I can double check.

**Comment by astrofrog** [comment]
I have come up with a regression test that causes the segfault and have pushed it to this PR. I have also temporarily reverted @saimn's change so that we can double check that a segfault does indeed happen in the CI.

**Comment by astrofrog** [comment]
Ok so confirming this causes a segfault:

Screenshot 2023-10-19 at 13 45 49

I'll remove the revert commit.

**Review by astrofrog — APPROVED** [review]
This looks good to me now, but @saimn please check the test I added!

File: astropy/io/fits/hdu/compressed/tests/test_tiled_compression.py
Comment (pllim) [inline astropy/io/fits/hdu/compressed/tests/test_tiled_compression.py:1]: Magical!

**Comment by saimn** [comment]
Excellent, thanks @astrofrog !
Let's merge this and we can address the remaining issues in  #15482 later.
