### PR TITLE
Guard against memory unmapping errors

### LINKED ISSUE #3118: A few unhandled errors in io.fits.compression module
A support request led me to track down a possible unhandled memory error in the compression module; specifically there is no MemoryError exception set in case this calloc call fails:

https://github.com/astropy/astropy/blob/master/astropy/io/fits/src/compressionmodule.c#L770

That causes the buffer pointer to return NULL here:

https://github.com/astropy/astropy/blob/master/astropy/io/fits/src/compressionmodule.c#L921

which is correct except that it doesn't set a Python exception to raise, resulting in

```
SystemError: error return without exception set
```

There are a couple other possible (though unlikely) error conditions in `init_output_buffer`, such as a missing ZNAXIS keyword, that are not properly handled either.  The thing to do would be to make the appropriate `PyErr_SetString` calls anywhere in `init_output_buffer` that can return an error condition.

### PR DESCRIPTION
**Pull request by mhvk**
This is an update of #4585, which ensures we don't get stack traces from badly corrupted compressed data hdus. It makes an additional change so that the code actually works as advertised (initializing `*buf=NULL`), simplifies it a bit, adds an extra error message, and adds tests.

fixes #3118

### CODE REVIEW

**Comment by mhvk** [comment]
@MSeifert04, @pllim - I think this is OK -- at least it provable avoids getting a complete breakdown, stacktrace included -- but a closer look is most welcome...

@embray - if you have time, could you check that this indeed fixes #3118?

File: astropy/io/fits/src/compressionmodule.c [hunk 1]
```diff
@@ -764,6 +768,13 @@ void init_output_buffer(PyObject* hdu, void** buf, size_t* bufsize) {
     }
 
     *buf = calloc(*bufsize, sizeof(char));
+    if (*buf == NULL) {
+      // Checking if calloc failed.
+      PyErr_SetString(PyExc_TypeError,
```
Comment (MSeifert04) [inline astropy/io/fits/src/compressionmodule.c]: This should be a `PyExc_MemoryError` and the next line has inconsistent indentation.

File: astropy/io/fits/src/compressionmodule.c [hunk 2]
```diff
@@ -888,7 +899,7 @@ PyObject* compression_compress_hdu(PyObject* self, PyObject* args)
     PyObject* retval = NULL;
     tcolumn* columns = NULL;
 
-    void* outbuf;
+    void* outbuf = NULL;
```
Comment (MSeifert04) [inline astropy/io/fits/src/compressionmodule.c]: Is this needed? I'm only asking out of curiosity.

File: CHANGES.rst [hunk 3]
```diff
@@ -204,6 +204,9 @@ Bug Fixes
 
   - Fix out-of-order TUNITn cards when writing tables to FITS. [#5720]
 
+  - Guard against extremely unlikely problems in compressed images, which
+    could lead to memory unmapping errors.
```
Comment (MSeifert04) [inline CHANGES.rst]: PR number is missing. :)

File: astropy/io/fits/src/compressionmodule.c (hunk 1 above)
Comment (mhvk) [inline astropy/io/fits/src/compressionmodule.c]: OK, makes sense, done.

File: astropy/io/fits/src/compressionmodule.c (hunk 2 above)
Comment (mhvk) [inline astropy/io/fits/src/compressionmodule.c]: Yes, it turned out that was in fact the most important change I still had to make -- the problem is that `init_output_buffer` does not touch `outbuf` at all when an error occurs and then the comparison with `NULL` fails, leading to a later trial to unmap `buf`.

(I guess an alternative would be to check for `PyErr_Occurred` or to let `init_output_buffer` return or set a status flag.)

Comment (pllim) [inline astropy/io/fits/src/compressionmodule.c]: I don't see anything wrong just setting it to NULL anyway.

Comment (mhvk) [inline astropy/io/fits/src/compressionmodule.c]: Agreed; overall, it seemed best to just keep any individual piece of code as little reliant as possible on the rest being correct...

**Comment by mhvk** [comment]
OK, I fixed the indentation and added the PR number to the changelog. (I used `[skip ci]` since this should not change anything, but checked it locally just to be sure).

Ready to go in?

**Comment by pllim** [comment]
LGTM :+1:   Thanks!

**Comment by MSeifert04** [comment]
👍 Thanks
